//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindFusion.Spreadsheet.Wpf.Samples.CS.Features.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindFusion.Spreadsheet.Wpf.Samples.CS.Features.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;workbook&gt;
        ///  &lt;worksheets&gt;
        ///    &lt;worksheet name=&quot;Sheet1&quot; defaultColumnWidth=&quot;48pt&quot; defaultRowHeight=&quot;14.25pt&quot;&gt;
        ///      &lt;columnStyles&gt;
        ///        &lt;region&gt;
        ///          &lt;lines&gt;
        ///            &lt;l ymin=&quot;0&quot; ymax=&quot;1&quot;&gt;
        ///              &lt;segments&gt;
        ///                &lt;s p=&quot;3&quot; s=&quot;1&quot; /&gt;
        ///                &lt;s p=&quot;4&quot; s=&quot;0&quot; /&gt;
        ///              &lt;/segments&gt;
        ///            &lt;/l&gt;
        ///          &lt;/lines&gt;
        ///          &lt;bounds x=&quot;3&quot; y=&quot;0&quot; width=&quot;1&quot; height=&quot;1&quot; /&gt;
        ///          &lt;style t=&quot;1&quot;&gt;
        ///            &lt;width&gt;68.25p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AutoFilter {
            get {
                return ResourceManager.GetString("AutoFilter", resourceCulture);
            }
        }
    }
}
